### ISSUE TITLE
Wrong link in documentation

### ISSUE THREAD

**Issue by Aunsiels** [ProofDrivenQuerying/pdq#10]
The first link (_parameter files_) on this page: https://github.com/ProofDrivenQuerying/pdq/wiki/Input-files is broken. It points to [https://github.com/ProofDrivenQuerying/pdq/wiki/Input-files#parameter-files](https://github.com/ProofDrivenQuerying/pdq/wiki/Input-files#parameter-files) but it should point to [https://github.com/ProofDrivenQuerying/pdq/wiki/Parameter-files#parameter-files](https://github.com/ProofDrivenQuerying/pdq/wiki/Parameter-files#parameter-files).

**Comment by michaelbenedikt** [comment]
Thanks very much Julien; I think I've fixed it.

**Comment by Aunsiels** [comment]
I also think the navigation section of the welcome page of the wikipedia is not up-to-date [https://github.com/ProofDrivenQuerying/pdq/wiki#navigation](https://github.com/ProofDrivenQuerying/pdq/wiki#navigation)

**Comment by michaelbenedikt** [comment]
Hopefully also fixed now
