### ISSUE TITLE
Default plannerType missing in documentation

### ISSUE THREAD

**Issue by Aunsiels** [ProofDrivenQuerying/pdq#11]
In [https://github.com/ProofDrivenQuerying/pdq/wiki/Parameter-files#planner](https://github.com/ProofDrivenQuerying/pdq/wiki/Parameter-files#planner), the default plannerType is not mentioned. I think it is DAG_OPTIMIZED given [https://github.com/ProofDrivenQuerying/pdq/blob/master/planner/main/src/uk/ac/ox/cs/pdq/planner/PlannerParameters.java#L243](https://github.com/ProofDrivenQuerying/pdq/blob/master/planner/main/src/uk/ac/ox/cs/pdq/planner/PlannerParameters.java#L243).

**Comment by michaelbenedikt** [comment]
fiexed
